#%RAML 1.0 NamedExample
value:
  order_id: 1
  order_date: "2023-09-15"
  product:
    product_id: 1
    product_name: "Product A"
    unit_price: 19.99
    in_stock: 100
    description: "High-quality product A"
  total_amount: 5
  status: "Shipped"